### PR TITLE
integrate sl-link functions w/ default org-link function

### PR DESCRIPTION
**Pull request by tpeacock19**
When outside org-buffers sl-store-link will fallback to
org-store-link. Similarly, when no sl-link marker, sl-insert-link
will fallback to org-insert-link.

----

#

### CODE REVIEW

**Comment by toshism** [comment]
Hey, thanks!  

Could you explain the use case behind this a bit? `sl-store-link` and `sl-insert-link` should work with non-org buffers currently, but maybe I don't quite understand the situation this solves?

**Comment by tpeacock19** [comment]
No problem, I initially saw the issue when I wanted to edit the
description of existing links in org-mode. =sl-insert-link= offer no ability to
edit while calling =org-insert-link= interactively does.

=sl-store-link= does not seem to work with =org-pdf-tools=. =org-pdf-tools= offers an interactive process of storing a link and the current =sl-store-link= method does not call that until =sl--insert-link= which breaks the workflow because you need to be on the pdf page. Also this format would allow for users to continue to use =C-u= to ignore context, skip custom storing functions, and store org-links en masse.

Ultimately, this should help to lessen the effect =org-super-links= has on default org-link functions.

**Comment by toshism** [comment]
Ah interesting, thanks for the explanation. Edit link would be really nice to have. I'll check it out. 

Thanks!

**Comment by toshism** [comment]
@tpeacock19 hey, i still haven't had time to test this. Are you no longer interested in having it included?

**Pull request closed without merging**
