### PR TITLE
Keep the original narrowing states

### PR DESCRIPTION
**Pull request by akirak**
When I use `org-super-links-insert-link` function, it widens the buffer where the function is called. I find it inconvenient especially when I insert a super link into an `org-capture` buffer.

You can restore the initial narrowing state using `save-restriction`, so I have wrapped all places that call `widen`.

### CODE REVIEW

**Comment by toshism** [comment]
Great, thanks @akirak ! I've been meaning to fix this one.

**Comment by stefan2904** [comment]
I guess this also fixes https://github.com/toshism/org-super-links/issues/70#issuecomment-1271600752 - I will check. Thanks a lot Akira!

**Comment by toshism** [comment]
Yes it should fix your issue in #70 @stefan2904 . Let me know if you still see an issue though.

**Comment by akirak** [comment]
You're welcome. Thank you for creating this package.

**Pull request merged**
